/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.trading.siyakhisa.app.gui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Thato Keith Kujwane
 */
public class LoginWindow extends javax.swing.JFrame {
    
    private final Thread timer;
    /**
     * Creates new form LoginWindow
     */
    public LoginWindow() {
        initComponents();
        this.timer = new Thread(new Timer(timeDisplay), "Timer");
        
        final LoginWindow f = this;
        addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent evt){
                int ans = JOptionPane.showConfirmDialog(f, "Are you sure you want to exit?", 
                        "Confirm Exit", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
                
                if (ans != JOptionPane.YES_OPTION){
                    
                }
            }
            
            @Override
            public void windowClosed(WindowEvent e) {
                f.operateWindow();
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeDisplay = new javax.swing.JLabel();
        nameDisplay = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Siyakhisa Trading");
        setBackground(new java.awt.Color(102, 255, 51));
        setName("mainFrame"); // NOI18N

        timeDisplay.setText("Timer");

        nameDisplay.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 16)); // NOI18N
        nameDisplay.setText("Siyakhisa Trading");

        loginBtn.setBackground(new java.awt.Color(102, 153, 255));
        loginBtn.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        loginBtn.setText("Login");

        registerBtn.setBackground(new java.awt.Color(255, 102, 102));
        registerBtn.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        registerBtn.setText("Register Profile");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addComponent(timeDisplay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(registerBtn)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(timeDisplay)
                .addGap(18, 18, 18)
                .addComponent(nameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        UserCreationWindow userCreationWindow = new UserCreationWindow();
        dispose();
        userCreationWindow.operateWindow();
    }//GEN-LAST:event_registerBtnActionPerformed
    public void operateWindow(){
        timer.start();
        setVisible(true);
    }
    
    public static void main(String[] args) throws InterruptedException {
        LoginWindow loginWindow = new LoginWindow();
        loginWindow.operateWindow();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel nameDisplay;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel timeDisplay;
    // End of variables declaration//GEN-END:variables
}